#!/usr/bin/env bash

set -exuo pipefail

here="$(realpath $(dirname $0))"

. "$here/config.sh"

cd "$here/../etherpad-lite"

git checkout "$etherpad_base_revision"
git am ../etherpad-lite-patches/*.patch

cd "$here/../ep_author_neat"

git checkout "$ep_author_neat_base_revision"
git am ../ep_author_neat-patches/*.patch

cd "$here/../ep_comments_page"

git checkout "$ep_comments_page_base_revision"
git am ../ep_comments_page-patches/*.patch
