#!/usr/bin/env bash

set -exuo pipefail

here="$(realpath $(dirname $0))"

. "$here/config.sh"

cd "$here/.."

if [ ! -e etherpad-lite ]; then
	git clone https://github.com/ether/etherpad-lite
	cd "$here/../etherpad-lite"
	git checkout "$etherpad_base_revision"
fi

cd "$here/.."

if [ ! -e ep_author_neat ]; then
	git clone https://github.com/clkao/ep_author_neat
	cd "$here/../ep_author_neat"
	git checkout "$ep_author_neat_base_revision"
fi

cd "$here/.."

if [ ! -e ep_comments_page ]; then
	git clone https://github.com/ether/ep_comments_page
	cd "$here/../ep_comments_page"
	git checkout "$ep_comments_page_base_revision"
fi
