#!/usr/bin/env bash

set -exuo pipefail

here="$(realpath $(dirname $0))"

. "$here/config.sh"

cd "$here/../etherpad-lite"

git format-patch \
	--output-directory ../etherpad-lite-patches \
	"$etherpad_base_revision"

cd "$here/../ep_author_neat"

git format-patch \
	--output-directory ../ep_author_neat-patches \
	"$ep_author_neat_base_revision"

cd "$here/../ep_comments_page"

git format-patch \
	--output-directory ../ep_comments_page-patches \
	"$ep_comments_page_base_revision"
