#!/usr/bin/env bash

set -exuo pipefail

here="$(dirname $0)"

. "$here/config.sh"

cd "$here/../etherpad-lite"

# Install our patched version of these packages:
npm install git+file:///opt/app/ep_author_neat
npm install git+file:///opt/app/ep_comments_page
