#!/usr/bin/env bash

set -exuo pipefail

here="$(dirname $0)"

. "$here/config.sh"

cd "$here/../etherpad-lite"

# Install capnp
#
# capnp is used for posting Sandstorm "activities"
#
# As of Oct 2021: The npm package is out of date. The node14 branch of the git
# repo is used on Sandstorm itself now. `npm install kenton/node-capnp#<ref>`
# does not work as of now, so we install the way we do.
#
# `npm install <something>` seems to delete anything it doesn't
# recognize. Since this is a hack installation, run it after the proper npm
# installations.

# current tip of node14 branch. Using hash for reproducibility.
CAPNP_HASH=ca17e686f267e1fcce20a2ed9583847b4528cd8f

(cd node_modules && git clone https://github.com/kentonv/node-capnp.git capnp)
(cd node_modules/capnp && git checkout $CAPNP_HASH && npm install)
